name: 'Assign Random CODEOWNERS Reviewers'
description: 'Assign random CODEOWNERS reviewers to PRs based on the changes submitted.'
branding:
  icon: 'user-plus'
  color: 'red'
inputs:
  assign-from-changed-files:
    description: 'Whether to assign CODEOWNERS based on changes files or assign the global CODEOWNERS.'
    required: false
    default: 'true'
  reviewers-to-assign: 
    description: 'How many CODEOWNERS to assign. This assigns CODEOWNERS up to (including) the given number, unless the number reviewers have already been assigned.'
    required: true
    default: '2'
  assign-individuals-from-teams: 
    description: 'Whether to pick and assign random team members from CODEOWNER teams as reviewers.'
    required: false
    default: 'false'
outputs:
  assigned-codeowners:
    description: 'The team or users assigned.'
runs:
  using: 'node16'
  main: 'dist/assign.js'
