on: 
  push:
    # branches:
    #   - 'main'

concurrency: ci-${{ github.workflow }}-${{ github.ref }}
permissions: 
  contents: write
  packages: write
  deployments: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    name: Distribute

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn

    - name: Install production packages
      run: |
        yarn install --production

    - name: Remove development types
      run: |
        echo "Modified 'tsconfig.json':"
        cat tsconfig.json | jq '.compilerOptions.types = null'
        
        cat tsconfig.json

    - name: Build
      run: |
        yarn build

    - name: Setup SSH release token
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

    # - name: Add production dependencies
    #   uses: EndBug/add-and-commit@v9
    #   with: 
    #     add: 'node_modules --force'
    #   env: 
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Push changes
    #   uses: ad-m/github-push-action@v0.6.0
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
      