name: Verify Release Labels

on:
  pull_request:
    types:
    - opened
    - edited
    - labeled
    - unlabeled
    - synchronize

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify-release:
    name: Verify Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 0

    - name: Verify PR labels
      uses: docker://agilepathway/pull-request-label-checker:latest
      with:
        one_of: major,minor,patch,internal
        repo_token: ${{ secrets.GITHUB_TOKEN }}
